package foundation

import (
	"fmt"
	"path/filepath"
	"strings"
)

// GenerateWorkflows writes build.yml and dispatch-missing.yml for the package.
func GenerateWorkflows(deps Deps, meta Meta, cfg Config) error {
	meta = meta.Normalize()
	dir := cfg.WorkflowDir
	if dir == "" {
		dir = ".github/workflows"
	}
	if !filepath.IsAbs(dir) {
		dir = filepath.Join(deps.WorkDir, dir)
	}
	if err := deps.FS.MkdirAll(dir, 0o755); err != nil {
		return err
	}

	targets := append([]string(nil), meta.DefaultTargets...)
	if len(targets) == 0 {
		targets = []string{TargetLinuxAMD64, TargetLinuxAArch64}
	}

	matrix := ""
	for _, c := range cellsForTargets(targets) {
		matrix += fmt.Sprintf("          - target: %s\n            runner: %s\n", c.Target, c.Runner)
	}

	files := map[string]string{
		"build.yml":            gha(renderBuildWorkflow(meta.Name, matrix, strings.Join(targets, " "))),
		"dispatch-missing.yml": gha(renderDispatchWorkflow(meta.Name)),
	}
	for name, body := range files {
		path := filepath.Join(dir, name)
		if !cfg.ForceWrite {
			if _, err := deps.FS.Stat(path); err == nil {
				return fmt.Errorf("%w: %s", ErrWorkflowExists, path)
			}
		}
		if err := deps.FS.WriteFile(path, []byte(body), 0o644); err != nil {
			return err
		}
		deps.Logf("wrote %s", path)
	}
	return nil
}

type matrixCell struct {
	Target string
	Runner string
}

func cellsForTargets(targets []string) []matrixCell {
	out := make([]matrixCell, 0, len(targets))
	for _, t := range targets {
		out = append(out, matrixCell{Target: t, Runner: RunnerForTarget(t)})
	}
	return out
}

// RunnerForTarget maps package targets to GitHub-hosted runners.
func RunnerForTarget(target string) string {
	switch {
	case target == TargetLinuxAArch64 || target == "linux-arm64":
		return "ubuntu-24.04-arm"
	case strings.HasPrefix(target, "windows-") && (strings.Contains(target, "arm64") || strings.Contains(target, "aarch64")):
		return "windows-11-arm"
	case strings.HasPrefix(target, "windows-"):
		return "windows-latest"
	default:
		return "ubuntu-latest"
	}
}

// gha expands @{{expr}}@ → ${{ expr }} without colliding with bash [[ ]].
func gha(s string) string {
	s = strings.ReplaceAll(s, "@{{", "${{ ")
	s = strings.ReplaceAll(s, "}}@", " }}")
	return s
}

func renderBuildWorkflow(name, matrix, targetsJoined string) string {
	// Use @{{expr}}@ placeholders; gha() expands to ${{ expr }}
	return fmt.Sprintf(`# Generated by: go run . generate workflow
# Package: %s — thin matrix; Go binary owns prep + in-container work.
name: Build

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:
    inputs:
      version:
        description: 'Upstream release tag to build (e.g. llvmorg-21.1.0)'
        required: true
        type: string
      publish:
        description: 'Create GitHub Release and upload tarballs'
        required: false
        type: boolean
        default: false
      recreate:
        description: 'If publish: delete existing release then create fresh'
        required: false
        type: boolean
        default: false

concurrency:
  group: package-build-@{{github.event.inputs.version || github.event.pull_request.number || github.sha}}@
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  plan:
    runs-on: ubuntu-latest
    outputs:
      version: @{{steps.plan.outputs.version}}@
      publish: @{{steps.plan.outputs.publish}}@
      recreate: @{{steps.plan.outputs.recreate}}@
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
      - id: plan
        env:
          INPUT_VERSION: @{{github.event.inputs.version}}@
          INPUT_PUBLISH: @{{github.event.inputs.publish}}@
          INPUT_RECREATE: @{{github.event.inputs.recreate}}@
          GITHUB_EVENT_NAME: @{{github.event_name}}@
          GH_TOKEN: @{{secrets.GITHUB_TOKEN}}@
        run: mise exec -- go run . plan


  build:
    needs: plan
    strategy:
      fail-fast: false
      matrix:
        include:
%s    runs-on: @{{matrix.runner}}@
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
      - name: go run . build
        env:
          APC_TARGETS: @{{matrix.target}}@
          APC_IMAGE_TAG: ci
          APC_PUBLISH: "0"
          GH_TOKEN: @{{secrets.GITHUB_TOKEN}}@
        run: mise exec -- go run . build "@{{needs.plan.outputs.version}}@"
      - uses: actions/upload-artifact@v4
        with:
          name: %s-@{{needs.plan.outputs.version}}@-@{{matrix.target}}@
          path: target/@{{matrix.target}}@/*
          if-no-files-found: error
          retention-days: 14

  publish:
    needs: [plan, build]
    if: @{{needs.plan.outputs.publish == 'true'}}@
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
      - uses: actions/download-artifact@v4
        with:
          path: artifacts
      - name: Stage artifacts
        run: |
          set -euo pipefail
          mkdir -p target
          find artifacts -type f \( -name '*.tar.gz' -o -name '*.zip' \) | while read -r f; do
            base=$(basename "$f")
            case "$base" in
              *-linux-amd64.*)   d=target/linux-amd64 ;;
              *-linux-aarch64.*) d=target/linux-aarch64 ;;
              *-windows-amd64.*) d=target/windows-amd64 ;;
              *-windows-arm64.*) d=target/windows-arm64 ;;
              *) d=target/misc ;;
            esac
            mkdir -p "$d"
            cp -v "$f" "$d/"
          done
          find target -type f -ls
      - name: go run . publish
        env:
          GH_TOKEN: @{{secrets.GITHUB_TOKEN}}@
          APC_TARGETS: "%s"
        run: |
          recreate_flag=
          case "@{{needs.plan.outputs.recreate}}@" in true|1|yes) recreate_flag=--recreate ;; esac
          mise exec -- go run . publish $recreate_flag "@{{needs.plan.outputs.version}}@"
`, name, matrix, name, targetsJoined)
}

func renderDispatchWorkflow(name string) string {
	return fmt.Sprintf(`# Generated by: go run . generate workflow
# Package: %s — fan-out via: go run . list
name: Dispatch Missing Builds

on:
  workflow_dispatch:
    inputs:
      versions:
        description: 'Space-separated versions (empty = missing only, or all upstream if recreate)'
        required: false
        type: string
      publish:
        description: 'Pass publish=true to each Build run'
        required: false
        type: boolean
        default: false
      recreate:
        description: 'Empty versions → all upstream tags; also recreate releases on publish'
        required: false
        type: boolean
        default: false
      max:
        description: 'Cap how many versions to dispatch (0 = no cap). Newest N when set.'
        required: false
        type: string
        default: "0"

concurrency:
  group: dispatch-missing-@{{github.workflow}}@
  cancel-in-progress: false

permissions:
  contents: read
  actions: write

jobs:
  dispatch:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
      - name: Plan and dispatch Build runs
        env:
          GH_TOKEN: @{{secrets.GITHUB_TOKEN}}@
          GITHUB_REPOSITORY: @{{github.repository}}@
          INPUT_VERSIONS: @{{inputs.versions}}@
          INPUT_PUBLISH: @{{inputs.publish}}@
          INPUT_RECREATE: @{{inputs.recreate}}@
          INPUT_MAX: @{{inputs.max}}@
        run: |
          set -euo pipefail
          publish=false
          recreate=false
          case "${INPUT_PUBLISH:-false}" in true|1|yes|True) publish=true ;; esac
          case "${INPUT_RECREATE:-false}" in true|1|yes|True) recreate=true ;; esac
          max_n="${INPUT_MAX:-0}"
          max_n="${max_n// /}"
          [[ -n "$max_n" ]] || max_n=0

          mapfile -t versions < <(
            if [[ -n "${INPUT_VERSIONS// }" ]]; then
              # shellcheck disable=SC2086
              mise exec -- go run . list ${INPUT_VERSIONS}
            elif [[ "$recreate" == true ]]; then
              mise exec -- go run . list --all
            else
              mise exec -- go run . list
            fi
          )

          if [[ "$max_n" =~ ^[0-9]+$ ]] && [[ "$max_n" -gt 0 ]]; then
            if (( ${#versions[@]} > max_n )); then
              versions=("${versions[@]: -max_n}")
            fi
          fi

          {
            echo "## Dispatch plan (%s)"
            echo ""
            echo "- Count: **${#versions[@]}**"
            echo "- Publish: **${publish}**"
            echo "- Recreate: **${recreate}**"
          } >> "$GITHUB_STEP_SUMMARY"

          if ((${#versions[@]} == 0)); then
            echo "Nothing to dispatch."
            exit 0
          fi

          for v in "${versions[@]}"; do
            echo "→ workflow run Build version=$v publish=$publish recreate=$recreate"
            gh workflow run Build \
              -f version="$v" \
              -f publish="$publish" \
              -f recreate="$recreate"
          done
`, name, name)
}
